name: drone_factory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0 
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/icons/none.svg
      - assets/icons/sine.svg
      - assets/icons/triangle.svg
      - assets/icons/square.svg
      - assets/icons/sawtooth.svg
  fonts:
      - family: CocomatLight
        fonts:
          - asset: assets/fonts/CocomatLight-ZXY3.ttf
      - family: QuicksandRegular
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          
  uses-material-design: true
