name: drone_factory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
      - family: CocomatLight
        fonts:
          - asset: assets/fonts/CocomatLight-ZXY3.ttf
          
  uses-material-design: true
